spring.application.name=examination

server.port=8080

# Broker-Port: 1883: normal, 8883: TLS:
robot.mqtt.broker=ssl://192.168.7.27:8883
#robot.mqtt.broker=ssl://localhost:8883
robot.mqtt.client-id=java_subscriber

robot.mqtt.leader.pos-topic=leader/pos
robot.mqtt.leader.temp-topic=leader/temp
robot.mqtt.leader.volt-topic=leader/volt
robot.mqtt.leader.state-topic=system/state

robot.mqtt.follower.pos-topic=follower/pos
robot.mqtt.follower.temp-topic=follower/temp
robot.mqtt.follower.volt-topic=follower/volt
robot.mqtt.follower.state-topic=system/state

robot.mqtt.controller-id=java_controller_publisher
robot.mqtt.controller.topic=control

robot.mqtt.dashboard-id=java_dashboard_mode_publisher
robot.mqtt.dashboard.topic=dashboard/mode