# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-lerobot"
BBFILE_PATTERN_meta-lerobot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-lerobot = "6"

LAYERDEPENDS_meta-lerobot = "core"
LAYERSERIES_COMPAT_meta-lerobot = "mickledore"
